### ISSUE TITLE
About data=> q_seq, qshft_seqs

### ISSUE THREAD

**Issue by wonjunchoi-arc** [hcnoh/knowledge-tracing-collection-pytorch#7]
for q_seq, r_seq in batch:
        q_seqs.append(FloatTensor(q_seq[:-1]))
        r_seqs.append(FloatTensor(r_seq[:-1]))
        qshft_seqs.append(FloatTensor(q_seq[1:]))
        rshft_seqs.append(FloatTensor(r_seq[1:]))

Through the code above
When making q_seqs and qshft_seqs, q_seqs should cut one of the ends, and qshft_seqs should make data to include the cut end from q_seqs so that qshft_seqs will get the query value we want?

On the code, are you making qshft_seqs through q_seqs with cut ends?

Am I wrong??

Please answer me if you have a chance!

**Comment by hcnoh** [comment]
Yes. you are right.

qshft_seqs is the target value for the q_seqs. They can be obtained by slicing the same question sequence.
